version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env.example
    volumes:
      - ./backend:/app
    depends_on:
      - prometheus

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "5173:80"
    env_file:
      - .env.example
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: rag-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/fastapi_bot_dashboard.json
    depends_on:
      - prometheus


  prometheus:
    image: prom/prometheus
    container_name: rag-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_METRICS_PORT:-8001}:9090"

networks:
  default:
    name: rag-net
